import { Product } from '@/types/store';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'hp-razer-v2x',
    name: 'Razer BlackShark V2 X Gaming Headset',
    slug: 'razer-blackshark-v2-x',
    category: 'gaming',
    brand: 'Razer',
    badge: '🔥 Best Seller',
    price: 2999,
    originalPrice: 4999,
    rating: 4.7,
    reviewsCount: 1842,
    inStock: true,
    inventoryCount: 35,
    tags: ['gaming', 'headphones', 'under-3000', 'surround-sound', 'wired', 'esports', 'noise-cancelling', 'razer'],
    description: 'Competition-grade esports headset featuring Razer TriForce 50mm Drivers, HyperClear Cardioid Mic, and advanced passive noise cancellation.',
    features: [
      'Razer TriForce 50mm Neodymium Drivers',
      'HyperClear Cardioid Microphone with noise suppression',
      'Ultra-lightweight 240g design for marathon gaming',
      'Advanced passive noise cancellation ear cushions',
      '7.1 Surround Sound on PC 64-bit Windows'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Classic Black', hex: '#111827' },
      { name: 'Razer Green', hex: '#22c55e' },
      { name: 'Mercury White', hex: '#f8fafc' },
    ],
    specs: {
      'Frequency Response': '12 Hz – 28 kHz',
      'Driver Size': '50 mm Razer TriForce',
      'Weight': '240 grams',
      'Connection': '3.5mm Analog',
      'Microphone': 'HyperClear Cardioid',
      'Noise Cancelling': 'Advanced Passive Isolation',
    },
    warranty: '2-Year Official Razer Replacement Warranty',
    compatibleWith: ['acc-rgb-stand', 'acc-audio-splitter'],
    upsellReason: 'Gamers pairing the BlackShark V2 X usually add the Aluminum RGB Headphone Stand to protect their investment and keep their desk clean.'
  },
  {
    id: 'hp-cosmic-kronos',
    name: 'Cosmic Byte Equinox Kronos Wireless 7.1 Headphone',
    slug: 'cosmic-byte-equinox-kronos',
    category: 'gaming',
    brand: 'Cosmic Byte',
    badge: '⚡ Wireless Pick',
    price: 2899,
    originalPrice: 3999,
    rating: 4.5,
    reviewsCount: 960,
    inStock: true,
    inventoryCount: 22,
    tags: ['gaming', 'headphones', 'under-3000', 'wireless', '7.1', 'rgb', 'cosmic-byte'],
    description: 'Lag-free 2.4GHz ultra-low latency wireless gaming headset with immersive virtual 7.1 surround sound and vibrant RGB lighting.',
    features: [
      '2.4GHz Ultra-Low Latency Wireless + 3.5mm AUX mode',
      'Immersive 7.1 Virtual Surround Sound',
      'Detachable unidirectional noise reduction mic',
      'Breathable memory foam ear cushions',
      'Dynamic multi-color RGB lighting'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Stealth Black', hex: '#1e293b' },
      { name: 'Cosmic Blue', hex: '#0284c7' },
    ],
    specs: {
      'Latency': '< 20ms Ultra-Low Latency',
      'Battery Life': 'Up to 24 Hours continuous play',
      'Surround Sound': 'Virtual 7.1 Channel Audio',
      'Microphone': 'Detachable Noise Reduction',
      'Wireless Range': '10 meters (33 ft)',
    },
    warranty: '1-Year Cosmic Byte Brand Warranty',
    compatibleWith: ['acc-rgb-stand', 'pad-speed-xl'],
    upsellReason: 'Keep your wireless headset charged and displayed with the dual-port RGB stand.'
  },
  {
    id: 'hp-redragon-zeus',
    name: 'Redragon H510 Zeus 7.1 Surround Headset',
    slug: 'redragon-h510-zeus',
    category: 'gaming',
    brand: 'Redragon',
    badge: '💎 Value King',
    price: 2699,
    originalPrice: 3599,
    rating: 4.6,
    reviewsCount: 715,
    inStock: true,
    inventoryCount: 18,
    tags: ['gaming', 'headphones', 'under-3000', 'surround-sound', 'memory-foam', 'redragon'],
    description: 'Crystal-clear sound with 53mm audio drivers, memory foam ear pads, and independent in-line USB audio control box.',
    features: [
      '53mm Custom Tuned Sound Drivers',
      'Detachable noise-canceling microphone',
      'Multi-platform compatibility (PC, PS5, Xbox, Switch)',
      'Hardware EQ box with mic mute & volume controls',
      'Steel frame with premium leatherette headband'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Midnight Black', hex: '#0f172a' },
      { name: 'White Edition', hex: '#e2e8f0' },
    ],
    specs: {
      'Drivers': '53 mm Neodymium Drivers',
      'Frame': 'High-Tensile Steel Structure',
      'Ear Pads': 'Premium Memory Foam',
      'EQ Controller': 'Detachable USB Hardware EQ Box',
      'Compatibility': 'PC, Mac, PS5, Xbox Series X/S',
    },
    warranty: '1-Year Redragon Official Warranty',
    compatibleWith: ['acc-rgb-stand', 'acc-audio-splitter'],
    upsellReason: 'Add the dual-channel audio splitter for seamless audio and mic split on desktop setups.'
  },
  {
    id: 'audio-sennheiser-hd560s',
    name: 'Sennheiser HD 560S Audiophile Reference Headphones',
    slug: 'sennheiser-hd-560s',
    category: 'audio',
    brand: 'Sennheiser',
    badge: '🇩🇪 German Precision',
    price: 14990,
    originalPrice: 18990,
    rating: 4.9,
    reviewsCount: 1120,
    inStock: true,
    inventoryCount: 12,
    tags: ['audio', 'audiophile', 'open-back', 'reference', 'sennheiser', 'german-engineered'],
    description: 'German-engineered linear acoustic craft designed for audio enthusiasts and competitive gamers who demand surgical positional precision.',
    features: [
      'Open-back earcups facilitate natural expansion of sound waves',
      'Ergonomic Acoustic Refinement (E.A.R.) angled transducer technology',
      'Ultralight 240g chassis with velvet-soft velour earpads',
      'Accurate deep bass extension down to 12 Hz with zero distortion',
      'Detachable 3m cable with gold-plated 6.3mm plug + 3.5mm adapter'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Matte Charcoal', hex: '#18181b' },
    ],
    specs: {
      'Acoustic Principle': 'Open-back Dynamic Transducer',
      'Frequency Response': '6 Hz – 38,000 Hz (-10 dB)',
      'Impedance': '120 Ohms Reference Grade',
      'Sound Pressure Level': '110 dB (1 kHz / 1 Vrms)',
      'Country of Design': 'Germany',
    },
    warranty: '2-Year Sennheiser International Warranty',
    compatibleWith: ['acc-rgb-stand'],
    upsellReason: 'Audiophiles and pros pair the HD 560S with a dedicated desktop stand to safeguard the open-back acoustic mesh.'
  },
  {
    id: 'mouse-logitech-superlight2',
    name: 'Logitech G PRO X Superlight 2 Lightspeed Mouse',
    slug: 'logitech-g-pro-x-superlight-2',
    category: 'peripherals',
    brand: 'Logitech',
    badge: '🏆 Esports Champion',
    price: 14995,
    originalPrice: 16995,
    rating: 4.9,
    reviewsCount: 2840,
    inStock: true,
    inventoryCount: 20,
    tags: ['gaming', 'mouse', 'wireless', 'lightspeed', 'logitech', 'esports', '32k-dpi'],
    description: 'The definitive pro esports mouse, weighing an astonishing 60 grams with HERO 2 sensor, 32,000 DPI, and LIGHTFORCE hybrid optical-mechanical switches.',
    features: [
      'Ultralightweight 60g design engineered with pro gamers',
      'HERO 2 Next-Gen Sensor with up to 32,000 DPI tracking',
      'LIGHTFORCE hybrid optical-mechanical switch technology',
      'LIGHTSPEED wireless with up to 95 hours continuous battery life',
      'Zero-additive PTFE mouse feet for frictionless gliding'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Obsidian Black', hex: '#0a0a0a' },
      { name: 'Chroma White', hex: '#fafafa' },
      { name: 'Magenta Pink', hex: '#db2777' },
    ],
    specs: {
      'Weight': '60 grams (< 2.2 oz)',
      'Sensor': 'HERO 2 Optical (100 - 32,000 DPI)',
      'Polling Rate': 'Up to 2,000 Hz / 4,000 Hz Wireless',
      'Switches': 'LIGHTFORCE Hybrid Optical-Mechanical',
      'Battery Life': '95 Hours continuous movement',
    },
    warranty: '2-Year Logitech G Limited Hardware Warranty',
    compatibleWith: ['pad-speed-xl', 'kb-steelseries-apexpro'],
    upsellReason: 'Maximize precision targeting with the GlideMaster Extended RGB mat.'
  },
  {
    id: 'kb-steelseries-apexpro',
    name: 'SteelSeries Apex Pro TKL HyperMagnetic Keyboard',
    slug: 'steelseries-apex-pro-tkl',
    category: 'keyboards',
    brand: 'SteelSeries',
    badge: '⚡ World’s Fastest',
    price: 18999,
    originalPrice: 22999,
    rating: 4.8,
    reviewsCount: 1490,
    inStock: true,
    inventoryCount: 14,
    tags: ['keyboards', 'mechanical', 'hypermagnetic', 'steelseries', 'rapid-trigger', 'oled'],
    description: 'World’s fastest keyboard with OmniPoint 2.0 adjustable hypermagnetic switches, Rapid Trigger 0.1mm actuation, and integrated smart OLED display.',
    features: [
      'OmniPoint 2.0 Adjustable HyperMagnetic Hall Effect Switches',
      'Rapid Trigger technology for instantaneous zero-latency resets',
      'Actuation customizable from 0.1mm to 4.0mm per key',
      'Integrated OLED Smart Display for Discord & system stats',
      'Aircraft-grade Series 5000 aluminum alloy top plate'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Jet Black Titanium', hex: '#09090b' },
    ],
    specs: {
      'Key Switches': 'OmniPoint 2.0 Adjustable Hall Effect',
      'Response Time': '0.7ms Rapid Response',
      'Actuation Range': '0.1 mm – 4.0 mm (40 levels)',
      'Chassis Material': 'Aircraft-Grade Aluminum Alloy',
      'Display': 'OLED Smart Information Center',
    },
    warranty: '2-Year SteelSeries Manufacturer Warranty',
    compatibleWith: ['mouse-logitech-superlight2', 'pad-speed-xl'],
    upsellReason: 'Complete your hyper-performance battlestation setup.'
  },
  {
    id: 'stream-elgato-deck',
    name: 'Elgato Stream Deck MK.2 Studio Audio Controller',
    slug: 'elgato-stream-deck-mk2',
    category: 'streaming',
    brand: 'Elgato',
    badge: '🎙️ Creator Essential',
    price: 13499,
    originalPrice: 15999,
    rating: 4.8,
    reviewsCount: 1780,
    inStock: true,
    inventoryCount: 16,
    tags: ['streaming', 'audio', 'elgato', 'macro', 'lcd-keys', 'creator'],
    description: 'Tactile control console featuring 15 customizable LCD keys to control audio streams, apps, OBS scenes, RGB lightning, and sound effects with one tap.',
    features: [
      '15 customizable LCD keys with visual feedback',
      'One-touch tactile operation for audio, streaming, and macros',
      'Interchangeable magnetic faceplates for personalized style',
      'Direct integration with OBS, Twitch, Spotify, Discord, Philips Hue',
      'Smart Profiles that adapt automatically when switching apps'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Deep Space Black', hex: '#171717' },
      { name: 'Alpine White', hex: '#f4f4f5' },
    ],
    specs: {
      'Keys': '15 customizable tactile LCD keys',
      'Interface': 'USB 2.0 High-Speed',
      'Stand': '45-Degree Fixed Angle Anti-Slip Stand',
      'Dimensions': '118 x 84 x 25 mm (4.6 x 3.3 x 1.0 in)',
      'Weight': '145 g without stand',
    },
    warranty: '2-Year Corsair Elgato Warranty',
    compatibleWith: ['audio-sennheiser-hd560s', 'acc-rgb-stand'],
    upsellReason: 'Control your audio levels and switch headphone profiles instantly with physical keys.'
  },
  {
    id: 'mon-samsung-odyssey-g7',
    name: 'Samsung Odyssey G7 28" 4K UHD 144Hz IPS Monitor',
    slug: 'samsung-odyssey-g7-4k',
    category: 'monitors',
    brand: 'Samsung',
    badge: '🖥️ 4K Visual Apex',
    price: 39999,
    originalPrice: 52999,
    rating: 4.8,
    reviewsCount: 650,
    inStock: true,
    inventoryCount: 8,
    tags: ['monitors', '4k', '144hz', 'ips', 'hdr400', 'g-sync', 'samsung', 'luxury'],
    description: 'Flagship 4K UHD gaming display with 144Hz refresh rate, 1ms response time, NVIDIA G-Sync compatibility, and immersive CoreSync RGB lighting.',
    features: [
      'Ultra HD 4K (3840 x 2160) IPS panel with 178° viewing angles',
      '144Hz lightning refresh rate + 1ms GtG response time',
      'NVIDIA G-Sync Compatible & AMD FreeSync Premium Pro',
      'VESA DisplayHDR 400 for intense contrast and color accuracy',
      'CoreSync rear ambient lighting projects your in-game colors onto the wall'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Titanium Black', hex: '#0f172a' },
    ],
    specs: {
      'Resolution': '3840 x 2160 (4K UHD 16:9)',
      'Panel Type': 'Super IPS with 90% DCI-P3',
      'Refresh Rate': '144 Hz with FreeSync / G-Sync',
      'Response Time': '1ms (GtG)',
      'Connectivity': '2x HDMI 2.1, 1x DisplayPort 1.4',
    },
    warranty: '3-Year Samsung On-Site Premium Warranty',
    compatibleWith: ['stream-elgato-deck', 'mouse-logitech-superlight2'],
    upsellReason: 'Experience the ultimate 4K fidelity matching your pro audio and peripherals setup.'
  },
  {
    id: 'ctrl-xbox-carbon',
    name: 'Xbox Wireless Controller Carbon Black + PC Adapter',
    slug: 'xbox-wireless-controller-carbon',
    category: 'controllers',
    brand: 'Microsoft',
    badge: '🎮 Pro Controller',
    price: 5390,
    originalPrice: 6990,
    rating: 4.7,
    reviewsCount: 3890,
    inStock: true,
    inventoryCount: 26,
    tags: ['controllers', 'gamepad', 'wireless', 'xbox', 'microsoft', 'bluetooth'],
    description: 'Modern ergonomic gaming controller with sculpted surfaces, hybrid D-pad, textured grip on triggers, and bundled Windows 11 wireless adapter.',
    features: [
      'Sculpted geometry and refined geometry for effortless comfort',
      'Hybrid D-pad with tactile directional feedback',
      'Textured grip on triggers, bumpers, and back case',
      'Dedicated Share button for capturing screenshots and clips',
      'Includes official Xbox Wireless USB Adapter for ultra-low latency PC gaming'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Carbon Black', hex: '#1c1917' },
      { name: 'Robot White', hex: '#f8fafc' },
      { name: 'Pulse Red', hex: '#dc2626' },
    ],
    specs: {
      'Connectivity': 'Xbox Wireless Adapter + Bluetooth 5.2 + USB-C',
      'Battery': 'Up to 40 hours with 2x AA batteries',
      'Audio Port': '3.5 mm stereo headset jack',
      'Rumble': 'Dual Impulse Triggers with haptic rumble',
      'Platform': 'Windows 10/11, Xbox Series X/S, iOS, Android',
    },
    warranty: '1-Year Microsoft Official Hardware Warranty',
    compatibleWith: ['hp-razer-v2x', 'acc-rgb-stand'],
    upsellReason: 'Plug your gaming headset directly into the 3.5mm controller jack for zero-cable sofa gaming.'
  },
  {
    id: 'acc-rgb-stand',
    name: 'Aura RGB Aluminum Headphone Stand with USB Hub',
    slug: 'aura-rgb-headphone-stand',
    category: 'accessories',
    brand: 'Aura',
    badge: '✨ Top Upsell',
    price: 699,
    originalPrice: 1299,
    rating: 4.8,
    reviewsCount: 520,
    inStock: true,
    inventoryCount: 45,
    tags: ['accessories', 'rgb', 'headphone-stand', 'usb-hub', 'desk-setup'],
    description: 'Sturdy weighted aluminum alloy headset holder with 10 dynamic RGB lighting modes and 2 built-in USB 2.0 pass-through ports.',
    features: [
      '10 Dynamic RGB Lighting Presets with touch sensor',
      '2x USB 2.0 pass-through ports for peripherals or charging',
      'Heavy non-slip weighted rubber base',
      'Universal fit for all over-ear gaming headsets',
      'Prevents ear cushion deformation over time'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584679109597-c656b19974c9?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Anodized Black', hex: '#111827' },
      { name: 'Silver Aluminum', hex: '#94a3b8' },
    ],
    specs: {
      'Base Material': 'CNC Weighted Aluminum Alloy',
      'Lighting': '10 RGB Chroma Lighting Modes',
      'USB Hub': '2x USB 2.0 Pass-Through Ports',
      'Height': '280 mm universal clearance',
    },
    warranty: '1-Year Aura Lifetime Build Guarantee',
    compatibleWith: ['hp-razer-v2x', 'hp-cosmic-kronos', 'audio-sennheiser-hd560s'],
    upsellReason: 'Essential desk accessory that prolongs headset life and adds 2 handy USB ports.'
  },
  {
    id: 'acc-audio-splitter',
    name: 'ProLine Gold-Plated 3.5mm Headset Splitter Cable',
    slug: 'proline-audio-splitter-cable',
    category: 'accessories',
    brand: 'ProLine',
    badge: '🔌 Essential',
    price: 299,
    originalPrice: 599,
    rating: 4.7,
    reviewsCount: 340,
    inStock: true,
    inventoryCount: 60,
    tags: ['accessories', 'cable', 'audio', 'splitter'],
    description: 'Tangle-free braided female 3.5mm to dual male mic/audio splitter with 24K gold-plated connectors for lossless audio transmission.',
    features: [
      '24K Gold-Plated connectors resist corrosion',
      'Durable military-grade braided nylon shielding',
      'Separates single combo 3.5mm jack into dedicated Mic & Audio jacks',
      'Zero audio latency or signal degradation'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Braided Black', hex: '#1e293b' },
    ],
    specs: {
      'Plating': '24K Real Gold Connectors',
      'Shielding': 'Double Braided Kevlar Core Nylon',
      'Length': '25 cm (10 inches)',
    },
    warranty: 'Lifetime Replacement Warranty',
    compatibleWith: ['hp-razer-v2x', 'hp-redragon-zeus'],
    upsellReason: 'Required if your PC tower has separate Mic and Headphone jacks.'
  },
  {
    id: 'pad-speed-xl',
    name: 'GlideMaster Extended RGB Gaming Mouse Pad (800x300mm)',
    slug: 'glidemaster-extended-rgb-mouse-pad',
    category: 'peripherals',
    brand: 'GlideMaster',
    badge: '⚡ Desk Mat',
    price: 499,
    originalPrice: 999,
    rating: 4.6,
    reviewsCount: 880,
    inStock: true,
    inventoryCount: 40,
    tags: ['peripherals', 'mousepad', 'rgb', 'accessories'],
    description: 'XXL micro-textured cloth gaming mat with 14 chroma RGB lighting modes, waterproof coating, and anti-slip rubber base.',
    features: [
      'Large 800 x 300 mm surface covers keyboard and mouse',
      '14 spectrum RGB lighting modes',
      'Waterproof nano-coating resists spill damage',
      'Ultra-smooth tracking for optical gaming sensors'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'RGB Cyber Matrix', hex: '#0f172a' },
    ],
    specs: {
      'Dimensions': '800 mm x 300 mm x 4 mm',
      'Surface': 'Micro-Weave Hydrophobic Fabric',
      'Lighting': '14 RGB Lighting Effects',
    },
    warranty: '1-Year Warranty',
    compatibleWith: ['mouse-logitech-superlight2', 'kb-steelseries-apexpro'],
    upsellReason: 'Complete your battlestation setup with matched RGB lighting.'
  },
  {
    id: 'mouse-hyperx-core',
    name: 'HyperX Pulsefire Core RGB Gaming Mouse',
    slug: 'hyperx-pulsefire-core',
    category: 'gaming',
    brand: 'HyperX',
    badge: '🎯 Budget Esports',
    price: 1499,
    originalPrice: 2490,
    rating: 4.7,
    reviewsCount: 1420,
    inStock: true,
    inventoryCount: 25,
    tags: ['gaming', 'mouse', 'rgb', 'pixart', 'hyperx'],
    description: 'Ergonomic gaming mouse with Pixart 3327 optical sensor up to 6200 DPI, 7 programmable buttons, and RGB customization.',
    features: [
      'Pixart 3327 optical sensor with native DPI up to 6,200',
      'Symmetrical design with textured side grips',
      '7 tactile programmable buttons rated for 20M clicks',
      'HyperX NGENUITY software customization'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Matte Black', hex: '#18181b' },
    ],
    specs: {
      'Sensor': 'Pixart PAW3327 (6,200 DPI)',
      'Buttons': '7 Programmable Omron Switches',
      'Weight': '87 grams',
    },
    warranty: '2-Year HyperX Official Warranty',
    compatibleWith: ['pad-speed-xl', 'kb-redragon-k552'],
    upsellReason: 'Pair your headset with precision esports targeting.'
  },
  {
    id: 'kb-redragon-k552',
    name: 'Redragon Kumara K552 RGB Mechanical Keyboard',
    slug: 'redragon-kumara-k552',
    category: 'keyboards',
    brand: 'Redragon',
    badge: '⌨️ Mechanical',
    price: 2799,
    originalPrice: 3999,
    rating: 4.6,
    reviewsCount: 2150,
    inStock: true,
    inventoryCount: 30,
    tags: ['keyboards', 'gaming', 'mechanical', 'rgb', 'compact', 'redragon'],
    description: 'Tenkeyless compact 87-key mechanical gaming keyboard with dustproof Outemu blue switches, solid metal alloy construction, and vibrant RGB backlighting.',
    features: [
      'Custom Outemu mechanical switches with tactile click',
      'Compact TKL 87-key space-saving layout',
      '18 RGB lighting backlighting presets',
      'Splash-proof aluminum and ABS construction',
      'Anti-ghosting 100% N-Key rollover'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Stealth Black', hex: '#09090b' },
      { name: 'Arctic White', hex: '#f1f5f9' },
    ],
    specs: {
      'Switches': 'Outemu Clicky Blue Switches',
      'Layout': 'TKL 87-Key Compact Form Factor',
      'Keycaps': 'Double-shot injection molded PBT/ABS',
      'Rollover': '100% Anti-Ghosting N-Key',
    },
    warranty: '1-Year Redragon Warranty',
    compatibleWith: ['pad-speed-xl', 'mouse-hyperx-core'],
    upsellReason: 'The #1 mechanical keyboard chosen by gamers in India under ₹3000.'
  },
  {
    id: 'audio-sony-ch520',
    name: 'Sony WH-CH520 Wireless Bluetooth Headphones',
    slug: 'sony-wh-ch520',
    category: 'audio',
    brand: 'Sony',
    badge: '🔋 50h Battery',
    price: 3990,
    originalPrice: 5990,
    rating: 4.6,
    reviewsCount: 3200,
    inStock: true,
    inventoryCount: 15,
    tags: ['audio', 'headphones', 'bluetooth', 'sony', 'wireless', 'battery'],
    description: 'Up to 50-hour battery life, DSEE sound upscaling, multipoint Bluetooth connection, and lightweight on-ear design.',
    features: [
      'Up to 50 hours battery life with quick charging',
      'DSEE sound digital enhancement technology',
      'Multipoint connection pairs two Bluetooth devices simultaneously',
      'Crystal clear hands-free calls with built-in mic'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Beige Cream', hex: '#d4c5b9' },
      { name: 'Navy Blue', hex: '#1e3a8a' },
    ],
    specs: {
      'Battery Life': 'Up to 50 hours (3 mins charge = 1.5h play)',
      'Audio Processing': 'Sony DSEE Sound Engine',
      'Weight': '147 grams Ultra-lightweight',
      'Multipoint': 'Pairs with 2 devices simultaneously',
    },
    warranty: '1-Year Sony India Brand Warranty',
    compatibleWith: ['acc-rgb-stand'],
    upsellReason: 'Ideal for both daily work commutes and music lovers.'
  }
];
